# Generated by Django 3.1.5 on 2021-03-06 09:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210306_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='special_user',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 6, 9, 50, 50, 88944, tzinfo=utc)),
        ),
    ]
